name: interval_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
