name: interval_timer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^6.0.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  just_audio: ^0.9.36
  material_design_icons_flutter: ^7.0.7296
  path_drawing: ^1.0.1
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  slide_to_act: ^2.0.2
  url_launcher: ^6.2.5
  xml: ^6.5.0
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/img/
    - assets/png/
    - .env