class BodyPartPositon {
  BodyPartPositon._(); // Private constructor

  static final BodyPartPositon _instance = BodyPartPositon._();

  factory BodyPartPositon() => _instance;

  static BodyPartPositon get instance => _instance;
  // Define positions and sizes for each body part
  Map<String, List<double>> frontPartPositions = {
    'leftLatissimus': [170, 90, 2.1],
    'leftKool': [150, 8, 0],
    'leftShoulder': [195, 33, 0],
    'leftBiceps': [200, 80, 0],
    'leftForearm': [200, 125, 0],
    'leftChest': [151, 40, 0],
    'leftFirstAb': [145, 87, 0],
    'leftSecondAb': [145, 110, 0],
    'leftThirdAb': [147, 133, 0],
    'leftSexAb': [157, 150, 2.7],
    'leftQuadFirst': [180, 167, .2],
    'leftQuadSecond': [170, 170, 0],
    'leftQuadThird': [159, 172, -.2],
    'leftFrontCraft': [175, 240, 0],
    'rightLatissimus': [75, 90, -2.1],
    'rightKool': [85, 8, 0],
    'rightShoulder': [47, 33, 0],
    'rightBiceps': [53, 80, 0],
    'rightForearm': [53, 125, 0],
    'rightChest': [91.5, 40, 0],
    'rightFirstAb': [103, 87, 0],
    'rightSecondAb': [105, 110, 0],
    'rightThirdAb': [107, 133, 0],
    'rightSexAb': [92, 153, .3],
    'rightQuadFirst': [96, 167, -.2],
    'rightQuadSecond': [108, 167, 0],
    'rightQuadThird': [118, 169, .2],
    'rightFrontCraft': [98, 240, 0],
  };

  Map<String, dynamic>? frontPartHowHard = {
    "leftLatissimus": [0, 0],
    "leftKool": [0, 0],
    "leftShoulder": [0, 0],
    "leftBiceps": [0, 0],
    "leftForearm": [0, 0],
    "leftChest": [0, 0],
    "leftFirstAb": [0, 0],
    "leftSecondAb": [0, 0],
    "leftThirdAb": [0, 0],
    "leftSexAb": [0, 0],
    "leftQuadFirst": [0, 0],
    "leftQuadSecond": [0, 0],
    "leftQuadThird": [0, 0],
    "leftFrontCraft": [0, 0],
    "rightLatissimus": [0, 0],
    "rightKool": [0, 0],
    "rightShoulder": [0, 0],
    "rightBiceps": [0, 0],
    "rightForearm": [0, 0],
    "rightChest": [0, 0],
    "rightFirstAb": [0, 0],
    "rightSecondAb": [0, 0],
    "rightThirdAb": [0, 0],
    "rightSexAb": [0, 0],
    "rightQuadFirst": [0, 0],
    "rightQuadSecond": [0, 0],
    "rightQuadThird": [0, 0],
    "rightFrontCraft": [0, 0]
  };

  Map<String, String> frontBodyColor = {
    "leftLatissimus": "glass",
    'leftKool': 'glass',
    'leftShoulder': 'glass',
    'leftBiceps': 'glass',
    'leftForearm': 'glass',
    'leftChest': 'glass',
    'leftFirstAb': 'glass',
    'leftSecondAb': 'glass',
    'leftThirdAb': 'glass',
    'leftSexAb': 'glass',
    'leftQuadFirst': 'glass',
    'leftQuadSecond': 'glass',
    'leftQuadThird': 'glass',
    'leftFrontCraft': 'glass',
    "rightLatissimus": "glass",
    'rightKool': 'glass',
    'rightShoulder': 'glass',
    'rightBiceps': 'glass',
    'rightForearm': 'glass',
    'rightChest': 'glass',
    'rightFirstAb': 'glass',
    'rightSecondAb': 'glass',
    'rightThirdAb': 'glass',
    'rightSexAb': 'glass',
    'rightQuadFirst': 'glass',
    'rightQuadSecond': 'glass',
    'rightQuadThird': 'glass',
    'rightFrontCraft': 'glass',
  };

  Map<String, List<double>> frontPartSizes = {
    'leftLatissimus': [40, 10],
    'leftKool': [50, 25],
    'leftShoulder': [40, 40],
    'leftBiceps': [30, 35],
    'leftForearm': [30, 45],
    'leftChest': [40, 40],
    'leftFirstAb': [33, 18],
    'leftSecondAb': [33, 18],
    'leftThirdAb': [27, 18],
    'leftSexAb': [37, 10],
    'leftQuadFirst': [7, 70],
    'leftQuadSecond': [6, 50],
    'leftQuadThird': [6, 60],
    'leftFrontCraft': [13, 50],
    'rightLatissimus': [40, 10],
    'rightKool': [50, 25],
    'rightShoulder': [40, 40],
    'rightBiceps': [30, 35],
    'rightForearm': [30, 45],
    'rightChest': [40, 40],
    'rightFirstAb': [33, 18],
    'rightSecondAb': [33, 18],
    'rightThirdAb': [27, 18],
    'rightSexAb': [37, 10],
    'rightQuadFirst': [7, 70],
    'rightQuadSecond': [6, 50],
    'rightQuadThird': [6, 60],
    'rightFrontCraft': [13, 50],
  };

//Back side

  Map<String, String> backBodyColor = {
    'rightBicepsFemoris': 'glass',
    'rightAdductor': 'glass',
    'rightSemitendinosus': 'glass',
    'leftSemitendinosus': 'glass',
    'leftBicepsFemoris': 'glass',
    'leftAdductor': 'glass',
    'rightKool': 'glass',
    'leftKool': 'glass',
    'rightTrapezius': 'glass',
    'leftTrapezius': 'glass',
    'rightMiddleHead': 'glass',
    'leftMiddleHead': 'glass',
    'rightPosteriorHead': 'glass',
    'leftPosteriorHead': 'glass',
    'rightTeres': 'glass',
    'leftTeres': 'glass',
    'rightLatissimusDorsi': 'glass',
    'leftLatissimusDorsi': 'glass',
    'rightLongHead': 'glass',
    'leftLongHead': 'glass',
    'rightLateralHead': 'glass',
    'leftLateralHead': 'glass',
    'rightMedialHead': 'glass',
    'leftMedialHead': 'glass',
    'rightAssist': 'glass',
    'leftAssist': 'glass',
    'leftErectorSpinae': 'glass',
    'rightErectorSpinae': 'glass',
    'rightGluteusMedius': 'glass',
    'leftGluteusMedius': 'glass',
    'rightGluteusMaximus': 'glass',
    'leftGluteusMaximus': 'glass',
    'rightSoleus': 'glass',
    'leftSoleus': 'glass',
    'leftGastrocnemius': 'glass',
    'rightGastrocnemius': 'glass',
    'rightIliotibial': 'glass',
    'leftIliotibial': 'glass',
    'rightExtemal': 'glass',
    'leftExtemal': 'glass',
  };

  Map<String, List<double>> backPartPositions = {
    'rightBicepsFemoris': [170, 90, 2.1],
    'rightAdductor': [150, 8, 0],
    'rightSemitendinosus': [195, 33, 0],
    'leftSemitendinosus': [200, 80, 0],
    'leftBicepsFemoris': [200, 125, 0],
    'leftAdductor': [151, 40, 0],
    'rightKool': [145, 87, 0],
    'leftKool': [145, 110, 0],
    'rightTrapezius': [147, 133, 0],
    'leftTrapezius': [157, 150, 2.7],
    'rightMiddleHead': [180, 167, .2],
    'leftMiddleHead': [170, 170, 0],
    'rightPosteriorHead': [159, 172, -.2],
    'leftPosteriorHead': [175, 240, 0],
    'rightTeres': [75, 90, -2.1],
    'leftTeres': [85, 8, 0],
    'rightLatissimusDorsi': [47, 33, 0],
    'leftLatissimusDorsi': [53, 80, 0],
    'rightLongHead': [53, 125, 0],
    'leftLongHead': [91.5, 40, 0],
    'rightLateralHead': [103, 87, 0],
    'leftLateralHead': [105, 110, 0],
    'rightMedialHead': [107, 133, 0],
    'leftMedialHead': [92, 153, .3],
    'rightAssist': [96, 167, -.2],
    'leftAssist': [108, 167, 0],
    'leftErectorSpinae': [118, 169, .2],
    'rightErectorSpinae': [98, 240, 0],
    'rightGluteusMedius': [98, 240, 0],
    'leftGluteusMedius': [170, 170, 0],
    'rightGluteusMaximus': [159, 172, -.2],
    'leftGluteusMaximus': [175, 240, 0],
    'rightSoleus': [75, 90, -2.1],
    'leftSoleus': [85, 8, 0],
    'leftGastrocnemius': [47, 33, 0],
    'rightGastrocnemius': [53, 80, 0],
    'rightIliotibial': [53, 125, 0],
    'leftIliotibial': [91.5, 40, 0],
    'rightExtemal': [103, 87, 0],
    'leftExtemal': [105, 110, 0],
  };

  Map<String, String> backPartHowHard = {
    'rightBicepsFemoris': 'glass',
    'rightAdductor': 'glass',
    'rightSemitendinosus': 'glass',
    'leftSemitendinosus': 'glass',
    'leftBicepsFemoris': 'glass',
    'leftAdductor': 'glass',
    'rightKool': 'glass',
    'leftKool': 'glass',
    'rightTrapezius': 'glass',
    'leftTrapezius': 'glass',
    'rightMiddleHead': 'glass',
    'leftMiddleHead': 'glass',
    'rightPosteriorHead': 'glass',
    'leftPosteriorHead': 'glass',
    'rightTeres': 'glass',
    'leftTeres': 'glass',
    'rightLatissimusDorsi': 'glass',
    'leftLatissimusDorsi': 'glass',
    'rightLongHead': 'glass',
    'leftLongHead': 'glass',
    'rightLateralHead': 'glass',
    'leftLateralHead': 'glass',
    'rightMedialHead': 'glass',
    'leftMedialHead': 'glass',
    'rightAssist': 'glass',
    'leftAssist': 'glass',
    'leftErectorSpinae': 'glass',
    'rightErectorSpinae': 'glass',
    'rightGluteusMedius': 'glass',
    'leftGluteusMedius': 'glass',
    'rightGluteusMaximus': 'glass',
    'leftGluteusMaximus': 'glass',
    'rightSoleus': 'glass',
    'leftSoleus': 'glass',
    'leftGastrocnemius': 'glass',
    'rightGastrocnemius': 'glass',
    'rightIliotibial': 'glass',
    'leftIliotibial': 'glass',
    'rightExtemal': 'glass',
    'leftExtemal': 'glass',
  };

  Map<String, List<double>> backPartSizes = {
    'leftBicepsFemoris': [40, 10],
    'rightBicepsFemoris': [40, 10],
    'leftAdductor': [50, 25],
    'rightAdductor': [50, 25],
    'leftSemitendinosus': [40, 40],
    'rightSemitendinosus': [40, 40],
    'leftKool': [30, 35],
    'rightKool': [30, 35],
    'leftTrapezius': [30, 45],
    'rightTrapezius': [30, 45],
    'leftMiddleHead': [40, 40],
    'rightMiddleHead': [40, 40],
    'leftPosteriorHead': [33, 18],
    'rightPosteriorHead': [33, 18],
    'leftTeres': [33, 18],
    'rightTeres': [33, 18],
    'leftLatissimusDorsi': [37, 10],
    'rightLatissimusDorsi': [37, 10],
    'leftLongHead': [7, 70],
    'rightLongHead': [7, 70],
    'leftLateralHead': [6, 50],
    'rightLateralHead': [6, 50],
    'leftMedialHead': [6, 60],
    'rightMedialHead': [6, 60],
    'leftAssist': [13, 50],
    'rightAssist': [13, 50],
    'leftErectorSpinae': [40, 10],
    'rightErectorSpinae': [40, 10],
    'leftGluteusMedius': [50, 25],
    'rightGluteusMedius': [50, 25],
    'leftGluteusMaximus': [40, 40],
    'rightGluteusMaximus': [40, 40],
    'leftSoleus': [30, 35],
    'rightSoleus': [30, 35],
    'leftGastrocnemius': [30, 45],
    'rightGastrocnemius': [30, 45],
    'leftIliotibial': [40, 40],
    'rightIliotibial': [40, 40],
    'leftExtemal': [33, 18],
    'rightExtemal': [33, 18],
  };
}
