// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0SMGf0EHku10F5k-yKqAh8Xyt4AjIHp0',
    appId: '1:761382146261:web:ce504e6f9ef3d4decc925c',
    messagingSenderId: '761382146261',
    projectId: 'luxfitpro',
    authDomain: 'luxfitpro.firebaseapp.com',
    storageBucket: 'luxfitpro.appspot.com',
    measurementId: 'G-4Q9G32WGSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAM4HxKaEvxf4DkMF6gRpdfkYWE2vBy78',
    appId: '1:761382146261:android:bbccfea78cf79163cc925c',
    messagingSenderId: '761382146261',
    projectId: 'luxfitpro',
    storageBucket: 'luxfitpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR__ZabhWqeFSueyNcMbPPAC3bz17rTr8',
    appId: '1:761382146261:ios:76a9d9f956d7d27bcc925c',
    messagingSenderId: '761382146261',
    projectId: 'luxfitpro',
    storageBucket: 'luxfitpro.appspot.com',
    iosBundleId: 'com.example.intervalTimer',
  );
}
