// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaDiR8q_b5UGcqM9ALrTqIR3uyFiIxu_c',
    appId: '1:871481562118:web:ce504e6f9ef3d4decc925c',
    messagingSenderId: '871481562118',
    projectId: 'lux-fit-pro',
    authDomain: 'lux-fit-pro.firebaseapp.com',
    storageBucket: 'lux-fit-pro.appspot.com',
    measurementId: 'G-4Q9G32WGSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaDiR8q_b5UGcqM9ALrTqIR3uyFiIxu_c',
    appId: '1:871481562118:android:02e9e81efd5844cb071f87',
    messagingSenderId: '871481562118',
    projectId: 'lux-fit-pro',
    storageBucket: 'lux-fit-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDiR8q_b5UGcqM9ALrTqIR3uyFiIxu_c',
    appId: '1:871481562118:ios:76a9d9f956d7d27bcc925c',
    messagingSenderId: '871481562118',
    projectId: 'lux-fit-pro',
    storageBucket: 'lux-fit-pro.appspot.com',
    iosBundleId: 'com.example.intervalTimer',
  );
}
